SELECT
    NODEID, AMPS, READINGTS,
    ROW_NUMBER() OVER (PARTITION BY NODEID ORDER BY AMPS DESC NULLS LAST) AS RN,
    RANK()       OVER (PARTITION BY NODEID ORDER BY AMPS DESC NULLS LAST) AS RNK,
    DENSE_RANK() OVER (PARTITION BY NODEID ORDER BY AMPS DESC NULLS LAST) AS DRNK
FROM reading
ORDER BY NODEID, RN;
