SELECT * FROM FROG;
SELECT * FROM WELL;

SELECT F.FROGID, F.FROGNAME, W.WELLID, W.WELLNAME
FROM FROG F
CROSS JOIN WELL W;

-- THIS IS A CROSS JOIN BETWEEN FROG AND WELL TABLES TO GET ALL POSSIBLE 
-- COMBINATIONS OF FROGS AND WELLS