
-- OBJECTIVE: COMBINE JUMP RECORDS WITH WELL_LINK DATA TO COMPARE 
--            THE VOLTS USED IN ACTUAL JUMPS VS THE EXPECTED VOLTS FOR THAT ROUTE.

SELECT
    J.JUMPID,           -- UNIQUE IDENTIFIER FOR EACH JUMP
    J.FROGID,           -- ID OF THE FROG THAT MADE THE JUMP
    J.FROMWELL,         -- STARTING WELL LOCATION
    J.TOWELL,           -- DESTINATION WELL LOCATION
    J.VOLTSSPENT,       -- ACTUAL ENERGY USED BY THE FROG
    WL.VOLTSCOST AS EXPECTEDCOST  -- EXPECTED ENERGY COST FOR THIS ROUTE
FROM JUMP J
JOIN WELLLINK WL
    ON J.FROMWELL = WL.FROMWELL
    AND J.TOWELL   = WL.TOWELL;
-- THIS RESULT SHOWS:
-- - EACH JUMP RECORD PAIRED WITH ITS CORRESPONDING ROUTE COST
-- - JUMPID: THE SPECIFIC JUMP EVENT BEING ANALYZED
-- - FROGID: WHICH FROG MADE THIS JUMP
-- - FROMWELL AND TOWELL: THE ROUTE TAKEN
-- - VOLTSSPENT VS EXPECTEDCOST: COMPARISON OF ACTUAL VS EXPECTED ENERGY
--   (HELPS IDENTIFY INEFFICIENT JUMPS WHERE VOLTSSPENT > EXPECTEDCOST,
--    OR ANOMALIES WHERE VOLTSSPENT < EXPECTEDCOST)

SELECT * FROM JUMP;
SELECT * FROM WELLLINK;