SELECT * FROM FROG;
SELECT * FROM WELL;
SELECT * FROM WELLLINK;
-- EACH WELL HAS A UNIQUE IDENTIFIER (WELLID) AND A NAME (WELLNAME).
-- THE HAZARD COLUMN INDICATES THE POTENTIAL HAZARDS ASSOCIATED WITH EACH WELL.
-- THIS COULD INCLUDE ENVIRONMENTAL RISKS, CONTAMINATION LEVELS, OR OTHER SAFETY CONCERNS.
-- THE VOLTSCOST IN THE WELLLINK TABLE MAY RELATE TO THE COST OF 
    -- ELECTRICITY OR ENERGY ASSOCIATED WITH THE WELL'S OPERATION.
SELECT
    F.FROGID,
    F.FROGNAME,
    WL.TOWELL,
    W.WELLNAME,
    W.HAZARD,
    WL.VOLTSCOST
FROM FROG F
JOIN WELLLINK WL
    ON WL.FROMWELL = F.HOMEWELLID
JOIN WELL W
    ON W.WELLID = WL.TOWELL
ORDER BY F.FROGID, W.HAZARD ASC, WL.VOLTSCOST ASC;
