
SELECT
    W1.FROMNODE AS STARTNODE,
    W1.TONODE   AS MIDNODE,
    W2.TONODE   AS ENDNODE
FROM WIRE W1
JOIN WIRE W2
    ON W1.TONODE = W2.FROMNODE
WHERE W1.ISLIVE = TRUE
    AND W2.ISLIVE = TRUE;
-- THIS QUERY FINDS ALL PAIRS OF LIVE WIRES WHERE THE END NODE OF THE FIRST WIRE
-- MATCHES THE START NODE OF THE SECOND WIRE EFFECTIVELY IDENTIFYING TWO-HOP PATHS