SELECT * FROM WIRE;
SELECT * FROM NODE;

SELECT
    W.WIREID,
    N1.NODENAME AS FROMNAME,
    N2.NODENAME AS TONAME,
    W.RESISTANCEOHM,
    W.ISLIVE
FROM WIRE W
JOIN NODE N1 ON N1.NODEID = W.FROMNODE
JOIN NODE N2 ON N2.NODEID = W.TONODE;
