
-- CORRECT: FILTER READINGS IN ON TO PRESERVE NODES WITH NO READINGS
SELECT N.NODEID, N.NODENAME, R.READINGTS, R.AMPS
FROM NODE N
LEFT JOIN READING R
    ON R.NODEID = N.NODEID
    -- filter condition goes here
    AND R.READINGTS >= '2026-01-20 10:01:00';
 
-- WRONG: THIS TURNS LEFT JOIN INTO INNER JOIN
SELECT N.NODEID, N.NODENAME, R.READINGTS, R.AMPS
FROM NODE N
LEFT JOIN READING R
    ON R.NODEID = N.NODEID
    -- here the filter is in WHERE clause so it 
    -- removes nodes with no readings
WHERE R.READINGTS >= '2026-01-20 10:01:00';

