SELECT
    N.ZONE,
    COUNT(DISTINCT N.NODEID) AS NODES,
    COUNT(R.READINGID) AS READINGS,
    ROUND(AVG(R.AMPS), 4) AS AVGAMPS
FROM NODE N
LEFT JOIN READING R ON R.NODEID = N.NODEID
GROUP BY N.ZONE;
