-- BEFORE
SELECT COUNT(*) AS JUMPROWS FROM JUMP;
 
-- AFTER JOIN
SELECT COUNT(*) AS JOINEDROWS
FROM JUMP J
JOIN WELLLINK WL
  ON J.FROMWELL = WL.FROMWELL AND J.TOWELL = WL.TOWELL;

-- THIS ALLOWS US TO VERIFY THAT EVERY JUMP HAS A CORRESPONDING WELLLINK ENTRY