SELECT
  COALESCE(J.FROMWELL, WL.FROMWELL) AS FROMWELL,
  COALESCE(J.TOWELL,   WL.TOWELL)   AS TOWELL,
  J.JUMPID,
  WL.VOLTSCOST
FROM JUMP J
FULL JOIN WELLLINK WL
  ON J.FROMWELL = WL.FROMWELL
AND J.TOWELL   = WL.TOWELL;
 
-- THIS SHOWS ALL WELLLINK ENTRIES AND ANY JUMP ENTRIES THAT DO NOT HAVE A CORRESPONDING WELLLINK ENTRY
-- I.E. WELLLINKS THAT WERE NOT USED FOR ANY JUMPS
