SELECT
  J.JUMPID, J.FROGID, J.FROMWELL, J.TOWELL,
  WL.VOLTSCOST
FROM JUMP J
LEFT JOIN WELLLINK WL
  ON J.FROMWELL = WL.FROMWELL
AND J.TOWELL   = WL.TOWELL
WHERE WL.VOLTSCOST IS NULL;
-- THERE ARE NO NULL RESULTS, MEANING ALL JUMPS HAVE CORRESPONDING WELLLINK ENTRIES.

SELECT * FROM JUMP;
SELECT * FROM WELLLINK;
